services:
  chancho:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - monquito
    volumes:
      - .:/home/app
  monquito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=josef  
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data
volumes:
  mongo-data: