services:
  chancho:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - monquito
    volumes:
      - .:/home/app
    environment: # <-- Usa esta secciÃ³n para pasar variables
      - DB_USER=${DB_USER}
      - API_KEY_SECRETA=${API_KEY_SECRETA}
  monquito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${API_KEY_SECRETA}
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/d
volumes:
  mongo-data: